### ISSUE TITLE
Estilizar o Github Pages

### ISSUE THREAD

**Issue by gabibguedes** [fga-eps-mds/2020-2-SiGeD#22]
## Descrição da issue

O MkDocs ainda está no formato em que é inicializado. Essa issue é para estilizar o MkDocs, de forma que esteja pronto para receber a documentação.

## Tasks:

- [x] Criar uma landing page inicial
- [x] Organizar a navegação do pages

## Critérios de aceitação:

- [x] O MkDocs está estilizado, organizado e pronto para receber a documentação do projeto
