### ISSUE TITLE
CRUD de usuários no backend

### ISSUE THREAD

**Issue by vitorl-s** [fga-eps-mds/2020-2-SiGeD#27]
## História:
Eu, como usuário desejo visualizar, adicionar, deletar e atualizar o cadastros de usuários no backend a fim de ter registros de usuários. 

Os dados do usuário devem ser: 

- Nome
- Email
- Matrícula
- Senha criptografada

## Tasks:

- [x] - Criação de usuarios
- [x] - Leitura de usuarios
- [x] - Atualização de usuários
- [x] - Remoção de usuários

## Critérios de aceitação:

- [x] - Conseguir criar, ler, remover e atualizar usuários
- [x] - Integração com o banco de dados
- [x] - Validação dos campos

**Comment by vitorl-s** [comment]
Essa issue entra na sprint 3 como débito técnico

**Comment by vitorl-s** [comment]
PR Merjado
