### ISSUE TITLE
Dockerizar o Backend

### ISSUE THREAD

**Issue by gabibguedes** [fga-eps-mds/2020-2-SiGeD#29]
## História:
Eu, como desenvolvedor desejo ter um ambiente dockerizado a fim de desenvolver o projeto com maior estabilidade

## Tasks:

- [x] - Criar docker para a aplicação Node.js
- [x] - Criar variáveis de ambiente para acesso ao banco de dados

## Critérios de aceitação:

- [x] -O ambiente pode ser executado e acessado normalmente via docker
