### ISSUE TITLE
Iniciar projeto do frontend

### ISSUE THREAD

**Issue by EzequielDeOliveira** [fga-eps-mds/2020-2-SiGeD#31]
História:
Eu, como desenvolvedor desejo ter uma base inicial para o projeto a fim de iniciar o desenvolvimento do frontend do projeto

## Tasks:

- [x] - Estrutura de pastas inicial
- [x] - Biblioteca de Icones
- [x] - Padrão de cores, como (Primary e secundary) 

## Critérios de aceitação:

- [x] - Ter uma estrutura inicial do projeto para possibilitar o inicio do desenvolvimento

**Comment by vitorl-s** [comment]
Projeto iniciado
