### ISSUE TITLE
Tela de cadastro de usuario

### ISSUE THREAD

**Issue by yukioz** [fga-eps-mds/2020-2-SiGeD#32]
## História:
Eu, como usuário desejo visualizar uma tela de cadastro com nome, e-mail, registro, senha e confirmação de senha a fim de ter meu cadastro feito na aplicação

## Tasks:

- [x] - Caixa de texto para nome do usuário
- [x] - Caixa de texto para e-mail do usuário
- [x] - Caixa de texto para registro do usuário
- [x] - Caixa de texto para senha do usuário
- [x] - Caixa de texto para confirmação da senha do usuário
- [x] - Botão para confirmar o cadastro
- [x] - Botão para cancelar o cadastro

## Critérios de aceitação:

- [x] - Seguir o design estabelecido da tela de cadastro
- [x] - Componentes para botão e inputs para tela de cadastro
- [x] - Atualização do componente lateral ao atualizar os campos
