### ISSUE TITLE
Tela de login do usuário

### ISSUE THREAD

**Issue by DafneM** [fga-eps-mds/2020-2-SiGeD#36]
## História:
Eu, como usuário desejo visualizar os campos de email, senha e as opções de entrada e cadastro a fim de entrar com meu login na aplicação.

O login do usuário deve ter 
- Nome
- Senha
- Botão para entrar
- Botão de cadastro
 
## Tasks:

- [x] - Criação do container para o login
- [x] - Leitura do email do usuário
- [x] - Leitura da senha do usuário
- [x] - Esconder senha
- [x] - Fazer botão para o usuário entrar
- [x] - Fazer botão para o usuário se cadastrar

## Critérios de aceitação:

- [x] - Conseguir mostrar na interface os campos de email, senha cadastro e entrar.
- [x] - Conseguir mostrar na interface os botões de entrar e cadastrar.
- [x] - Responsividade da tela.
- [x] - Componentização de campos de entrada e botões de cadastro e entrar.

**Comment by vitorl-s** [comment]
Issue finalizada, PR merjado
