### ISSUE TITLE
Iniciar o projeto do backend

### ISSUE THREAD

**Issue by GabrielOak** [fga-eps-mds/2020-2-SiGeD#37]
## História:
Eu, como desenvolvedor desejo ter uma base inicial para o projeto a fim de iniciar o desenvolvimento do backend

## Tasks:
- [x] - Criar um README explicando como rodar o projeto
- [x] - Organização das pastas 
- [x] - Configurações iniciais da api
- [x] - Configurações iniciais do banco de dados

## Critérios de aceitação:
- [x] - README criado 
- [x] - Pastas organizadas
- [x] - Configurações da api
- [x] - Configurações do banco

**Comment by vitorl-s** [comment]
Projeto Iniciado
