### ISSUE TITLE
Conexão da tela de cadastro com API e Validações

### ISSUE THREAD

**Issue by DaviMarinho** [fga-eps-mds/2020-2-SiGeD#47]
## História:

Eu, como usuário desejo poder me cadastrar na aplicação e ver os potenciais erros de formulários.

## Tasks:

- [x] - Conectar a tela de cadastro com a API
- [x] - Validar as informações fornecidas pelo usuário
- [x] - Tratar erros da API

## Critérios de aceitação:

- [x] - É possível cadastrar usuários pelo frontend
- [x] - O formulário de cadastro mostra possíveis erros
- [x] - Erros vindo da API corretamente tratados
