### ISSUE TITLE
Guia de estilo + CI

### ISSUE THREAD

**Issue by gabibguedes** [fga-eps-mds/2020-2-SiGeD#49]
## Descrição

Fazer guia de estilo padronizada.

## Tasks:

- [x] - Definir guia de estilo pra o frontend
- [x] - Definir guia de estilo para o backend
- [x] - Configurar um CI para bloquear os PRs com erros de guia de estilo do frontend
- [x] - Configurar um CI para bloquear os PRs com erros de guia de estilo do backend

## Critérios de aceitação:

- [x] - Guia de estilo bem definida no frontend e no backend
- [x] - CI configurado no frontend e no backend
- [x] - Não é possivel aceitar PRs com erros de guia de estilo

**Comment by gabibguedes** [comment]
O guia de estilo definido para o frontend e backend do projeto é o do AirBnb, pois é de grande referencia em projetos JS e contempla praticamente todos os aspectos.

**Comment by gabibguedes** [comment]
CI implementado nos repositorios
