### ISSUE TITLE
Lista de usuário

### ISSUE THREAD

**Issue by yukioz** [fga-eps-mds/2020-2-SiGeD#51]
História:
Eu, como administrador desejo visualizar uma lista de usuário cadastrados a fim de checar as pessoas cadastradas.

## Tasks:
- [x] - Filtro de busca de usuários
- [x] - Listar usuários.

## Critérios de aceitação:

- [x] - Correspondência com protótipo
- [x] - Conectar com API.
- [x] - Responsivo para Web.
