### ISSUE TITLE
Correção da tela de login

### ISSUE THREAD

**Issue by nYCSTs** [fga-eps-mds/2020-2-SiGeD#53]
## Descrição da issue

- Correção do posicionamento da tela de login 

## Tasks:

- [ ] - Corrigir posicionamento da tela de login
- [ ] - Ajustar a cor do botão "Entrar"

## Critérios de aceitação:

- [ ] - Funcionamento da tela de login com a navbar
- [ ] - Cor seguindo o padrão de alternância de cores
